junglists = [
    "4hero",
    "AK1200",
    "Adam F",
    "Alex Reece",
    "Amon Tobin",
    "Andy C",
    "Aphex Twin",
    "Aphrodite",
    "Aquasky",
    "Audio",
    "B-Complex",
    "Bachelors of Science",
    "Bad Company",
    "Billain",
    "Black Sun Empire",
    "Blame",
    "Blu Mar Ten",
    "Blanke",
    "Blue Stahli",
    "Michiel van den Bos",
    "Boymerang",
    "Breakbeat Era",
    "Justin Broadrick",
    "Brookes Brothers",
    "Danny Byrd",
    "DJ Bryan Gee",
    "Calibre",
    "Calyx",
    "Camo & Krooked",
    "Davide Carbone",
    "Cause 4 Concern",
    "Celldweller",
    "Chase & Status",
    "Commix",
    "Concord Dawn",
    "Corrupt Souls",
    "Counterstrike",
    "Crissy Criss",
    "Cui Jian",
    "Culture Shock",
    "Current Value",
    "D.Kay",
    "DBridge",
    "DC Breaks",
    "Dimension",
    "DJ Craze",
    "DJ Dara",
    "DJ Dextrous",
    "DJ Die",
    "DJ Food",
    "DJ Fresh",
    "DJ Hazard",
    "DJ Hidden",
    "DJ Hype",
    "DJ Kentaro",
    "DJ Marky",
    "DJ Patife",
    "DJ Rap",
    "DJ Ron",
    "DJ SS",
    "DJ Starscream",
    "DJ Zinc",
    "Danny Breaks",
    "Decoder",
    "DeeJay Delta",
    "Deekline",
    "Delta Heavy",
    "Demon Boyz",
    "Dieselboy",
    "Dillinja",
    "Dirtyphonics",
    "Dom & Roland",
    "Doubleclick",
    "Drumagick",
    "Drumsound & Bassline Smith",
    "Dwarf Electro",
    "E-Z Rollers",
    "Eresse",
    "Etherwood",
    "Evol Intent",
    "Tim Exile",
    "Eye-D",
    "Fabio",
    "The Flashbulb",
    "Freaky Flow",
    "Friction",
    "Fred V & Grafix",
    "Goldie",
    "The Glitch Mob",
    "Grooverider",
    "A Guy Called Gerald",
    "Gremlinz",
    "High Contrast",
    "Hybrid",
    "Hedex",
    "Ill.Skillz",
    "Ilk",
    "Imanu",
    "Ivy Lab",
    "Jade",
    "J Majik",
    "John B",
    "Jonny L",
    "Jordana",
    "Jumpin Jack Frost",
    "Keeno",
    "Ray Keith",
    "Kēvens",
    "Kemistry",
    "Kemistry & Storm",
    "Kenny Ken",
    "Kill the Noise",
    "Killbot",
    "Klute",
    "Konflict",
    "Kosheen",
    "Kove",
    "Koven",
    "Krust",
    "Kuuro",
    "LTJ Bukem",
    "Lamb",
    "Left Spine Down",
    "Lenzman",
    "Limewax",
    "Liondub",
    "LiveSummit",
    "Loadstar",
    "Logistics",
    "London Elektricity",
    "Luude",
    "Maduk",
    "Makoto",
    "Marcus Intalex",
    "Matrix",
    "MC Skibadee",
    "Metrik",
    "Michele Sainte",
    "Missrepresent",
    "Muzz",
    "Nanotek",
    "Nerve",
    "Netsky",
    "Nia Archives",
    "Noisia",
    "Nucleus",
    "Nu:Logic",
    "Nu:Tone",
    "Omni Trio",
    "Optical",
    "PH10",
    "The Panacea",
    "Panda",
    "Paradox",
    "Pendulum",
    "Alix Perez",
    "Peshay",
    "Phace",
    "Photek",
    "Plastikman",
    "Plug",
    "Podočnjaci",
    "Polar",
    "Pythius",
    "The Prodigy",
    "The Prototypes",
    "Q Project",
    "The Qemists",
    "Quoit",
    "Rabbit Junk",
    "Ragga Twins",
    "Ram Trilogy",
    "Rawtekk",
    "Tim Reaper",
    "Rebel MC",
    "Red Snapper",
    "Renegade Soundwave",
    "Replicator",
    "Roni Size & Reprazent",
    "Rregula",
    "Rudimental",
    "Ed Rush",
    "Salmonella Dub",
    "Doc Scott",
    "Seba",
    "Shapeshifter",
    "Shimon",
    "The Shizit",
    "ShockOne",
    "Shy FX",
    "Si Begg",
    "Sigma",
    "Slipmatt",
    "Ed Solo",
    "Source Direct",
    "Spectrum",
    "Spor",
    "Spring Heel Jack",
    "S.P.Y",
    "Squarepusher",
    "Stamina MC",
    "Stanton Warriors",
    "State of Mind",
    "Step 13",
    "Fox Stevenson",
    "Stevie Hyper D",
    "Sub Focus",
    "Submerged",
    "System 7",
    "T Power",
    "TC",
    "Tiki Taane",
    "Tabla Beat Science",
    "Nobukazu Takemura",
    "Teebee",
    "Soichi Terada",
    "Top Buzz",
    "Total Science",
    "Typecell",
    "U-ziq",
    "Vector Burn",
    "Venetian Snares",
    "Luke Vibert",
    "Wagon Christ",
    "Danny Wheeler",
    "Wickaman",
    "Wilkinson",
    "Witchman",
    "XRS",
    "Xample",
    "Zardonic"
]
# import secrets;s,o=set(),[]
# while s!=set(z:=junglists):(a:= secrets.choice(z)) and (""if a in s else (s.add(a) or o.append(a)))
# print(o[0])
import secrets as b;s,o=set(),[]
while len(o)<len(junglists):
    (a:=b.choice(junglists))not in s and (s.add(a)or o.append(a))
print(o)