z = '''
1. INTRODUCTION
2. IT’S GOING TO BE A STORM! DO YOU HAVE AN UMBRELLA?
3. THE ULTIMATE GUIDE TO FINDING A MENTOR
4. HOW TO HAVE 1,000 MENTORS IN YOUR LIFE
5. THE SEVEN TECHNIQUES TO INFLUENCE ANYONE
6. WHAT I LEARNED ABOUT NEGOTIATION FROM THE FBI’S BEST HOSTAGE NEGOTIATOR
7. THE TAO OF LOUIS C.K.
8. PEOPLE DON’T REMEMBER WHAT THEY DON’T LIKE
9. HOW TO GIVE A GIFT
10. HOW PICASSO PRODUCED 50,000 WORKS OF ART
11. HOW TO FIND YOUR CALLING
12. ARE YOU A PLUS, A MINUS, OR A ZERO?: LESSONS FROM AN ASTRONAUT
13. WHAT I LEARNED ABOUT PHOTOGRAPHY FROM CHASE JARVIS
14. SEVEN THINGS I LEARNED FROM MY EIGHT GREATEST TEACHERS
15. THIRTEEN THINGS WAYNE DYER PERSONALLY TAUGHT ME
16. FIVE THINGS I LEARNED FROM SUPERMAN
17. SEVEN THINGS STAR WARS TAUGHT ME ABOUT PRODUCTIVITY
18. WHAT I’VE LEARNED FROM ELON MUSK
19. SIX THINGS I’VE LEARNED FROM MICK JAGGER
20. IS POPE FRANCIS AN ATHEIST? (AND TEN OTHER THINGS I’VE LEARNED FROM HIM)
21. FIVE THINGS I’VE LEARNED FROM GANDHI
22. HOW TO GET AN MBA FROM EMINEM
23. NINE THINGS I LEARNED FROM SERENA WILLIAMS
24. SEVEN UNUSUAL THINGS I LEARNED FROM LOUIS ARMSTRONG
25. IF IT’S NOT HARD, IT’S SOFT
26. TEN THINGS I LEARNED FROM COOLIO
27. THE SECRET OF ALL ART
28. FIVE UNUSUAL THINGS I LEARNED FROM ISAAC ASIMOV
29. ARE YOU THERE, JUDY BLUME? IT’S ME, JAMES
30. SIX THINGS I LEARNED FROM CHARLES BUKOWSKI .
31. WHAT I LEARNED ABOUT LEADERSHIP FROM A NOTORIOUS DRUG DEALER
32. DAYMOND JOHN SCHOOLS ME ON “THE POWER OF BROKE”
33. HOW I HELPED MARK CUBAN MAKE $1 BILLION, AND WHAT I LEARNED FROM HIM 34. WHAT I LEARNED FROM “SHARK TANK”
35. TEN THINGS I LEARNED FROM INTERVIEWING TONY ROBBINS
36. EINSTEIN’S SECRET OF PRODUCTIVITY
37. THE TWENTY THINGS I’VE LEARNED FROM LARRY PAGE
38. MIMI’S THREE STEPS TO MAKE A MILLION
39. HOW TO LEARN TO DO THE IMPOSSIBLE
40. THE TEN THINGS I LEARNED FROM RICHARD BRANSON
41. GO DOWN THE RABBIT HOLE OF OUR INTERESTS: A LESSON FROM MALALA
42. DO YOU MAKE FEAR DECISIONS OR GROWTH DECISIONS?
43. DARE OF THE DAY
44. THREE THINGS I LEARNED FROM THE ULTIMATE CHOOSE YOURSELF-ER
45. THE DAY I CRUSHED MY THIRTEEN-YEAR-OLD
46. LESSONS I LEARNED FROM PLAYING POKER FOR 365 STRAIGHT DAYS
47. WHAT I LEARNED FROM CHESS
'''

for o in z.split('\n'):
    if o:
        print(f"<li>{' '.join(o.split(' ')[1:])}</li>")
